language: c
sudo: false

before_script:
  - ./build.sh

script:
  - ./builds/nojit/luajit simplerunner.lua 1
  - ./builds/normal/luajit simplerunner.lua --jitstats 3
  - ./builds/gc64/luajit simplerunner.lua 3
  - ./builds/dualnum/luajit simplerunner.lua 3
  - ./builds/raptorjit/luajit simplerunner.lua 3
