language: c
sudo: false

before_script:
  - ./build_luajit.sh

script:
  - ./builds/nojit/luajit simplerunner.lua
  - ./builds/normal/luajit simplerunner.lua
  - ./builds/gc64/luajit simplerunner.lua
  - ./builds/dualnum/luajit simplerunner.lua
  - ./builds/raptorjit/luajit simplerunner.lua
