language: c
sudo: false

before_script:
  - ./build.sh

script:
  - ./builds/nojit/luajit simplerunner.lua -c 1
  - ./builds/normal/luajit simplerunner.lua --jitstats -c 3
  - ./builds/gc64/luajit simplerunner.lua -e capnproto_decode -c 3
  - ./builds/dualnum/luajit simplerunner.lua -c 3
  - ./builds/raptorjit/luajit simplerunner.lua -e capnproto_decode -c 3
