language: c
sudo: false

before_script:
  - ./build_luajit.sh

script:
  - ./builds/luajit_nojit simplerunner.lua
  - ./builds/luajit simplerunner.lua
  - ./builds/luajit_gc64 simplerunner.lua
  - ./builds/luajit_dualnum simplerunner.lua